/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MapRouteImport } from './routes/map/route'

// Create Virtual Routes

const ContactRouteLazyImport = createFileRoute('/contact')()
const IndexRouteLazyImport = createFileRoute('/')()

// Create/Update Routes

const ContactRouteLazyRoute = ContactRouteLazyImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contact/route.lazy').then((d) => d.Route))

const MapRouteRoute = MapRouteImport.update({
  path: '/map',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/map/route.lazy').then((d) => d.Route))

const IndexRouteLazyRoute = IndexRouteLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index/route.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteLazyRoute,
  MapRouteRoute,
  ContactRouteLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/map",
        "/contact"
      ]
    },
    "/": {
      "filePath": "index/route.lazy.tsx"
    },
    "/map": {
      "filePath": "map/route.tsx"
    },
    "/contact": {
      "filePath": "contact/route.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
